feat: добавляет функцию генерирующую случайное число в заданном диапазоне
htmlacademy-javascript/1578925-keksobooking-23 pull request #2
Opened 2021-05-30 11:07 UTC by ZKseniya

2021-05-30 13:15 UTC, ArtMan-8 requested changes

2021-05-30 13:15 UTC, ArtMan-8 commented on index.html
> +  <script src="js/main.js"></script>
В текущем варианте подключения могут быть проблемы.
Лучше указывать относительный путь в таком виде `./js/main.js`,

2021-05-30 13:15 UTC, ArtMan-8 commented on js/main.js
> +  return number.toFixed(numberOfDemicalPlace);
Проверки не зависят от значения `number`, поэтому лучше их выполнять до него.

Интересный вариант с `Math.pow()`.

Функция должна возвращать число, а не строку.
Если не передать 3й аргумент, функция возвращает `NaN`.

2021-05-30 13:56 UTC, ZKseniya commented on js/main.js
> +  return number.toFixed(numberOfDemicalPlace);
Как здесь лучше поступить с 3 аргументом? Сделать вариант по умолчанию?

2021-05-30 14:31 UTC, ArtMan-8 commented on js/main.js
> +  return number.toFixed(numberOfDemicalPlace);
конечно,
если третьим аргументом ничего не передаётся, значит у него должно быть значение по умолчанию - в данном случае, оно должно приводить в результате к целому числу.

2021-05-31 05:39 UTC, ArtMan-8 approved these changes
Хорошо, от местоположения мин/макс не зависит.

2021-05-31 05:40 UTC, merged